export const types = {
    /* ---------- TPYE_DEFINE ---------- */
    // GET_TPYE_DEFINE_REQUEST: "APP/GET_TPYE_DEFINE_REQUEST",
    // GET_TPYE_DEFINE_SUCCESS: "APP/GET_TPYE_DEFINE_SUCCESS",
    // GET_TPYE_DEFINE_FAILURE: "APP/GET_TPYE_DEFINE_FAILURE",
    
    // 비동기 처리시 준비, 성공, 실패 단계로 나누어서 처리
    // GET_TITLE_POST_PENDING : "EVENT/GET_TITLE_POST_PENDING",
    // GET_TITLE_POST_SUCCESS : "EVENT/GET_TITLE_POST_SUCCESS",
    // GET_TITLE_POST_FAILURE : "EVENT/GET_TITLE_POST_FAILURE",
        
    SET_VISIBILITY_FILTER : "EVENT/SET_VISIBILITY_FILTER",
    TOGGLE_TODO : "EVENT/TOGGLE_TODO",

    SHOW_ALL: "EVENT/SHOW_ALL",
    SHOW_COMPLETED: "EVENT/SHOW_COMPLETED",
    SHOW_ACTIVE: "EVENT/SHOW_ACTIVE"

  };